### ISSUE TITLE
손녀 기준 화면 WireFrame 작업

### ISSUE THREAD

**Issue by effozen** [boostcampwm-2024/web28-DDara#101]
## 📌 요청 기능 설명

"손녀 화면에 대한 WireFrame 작업"

## 📝 기능 세부 사항

- 화면에 지도가 표시가 되어야 함
- 뒤로가기 버튼이 존재해야 함
- 우측 상단에 드로워가 존재해서, 해당 드로워를 바탕으로 보여지는 사용자를 선택할 수 있어야 함
- 우측 하단에 화면에 보여지는 사용자를 색상별로 해서 구분해서 표시해줘야 함
- 사용자 별 현재 위치와 경로, 도착 위치가 표시가 되어야 함.
- 권한이 없을 경우 할머니에게 자신의 경로만 보이게 제공한다고 생각하고 개발이 되어야 함.

## 🤔 기능 추가 배경 및 목적

손녀 기준에서 "Read"에 해당하는 화면, 현재 다른 사용자가 어디 쯤 왔는 지 보여줄 수 있어야 함.
여기서 그냥 자신의 경로만 보여주게 하면 할머니에게 보내주는 화면이 되기도 하므로, 이를 고려해서 개발할 것

## 🚩 완료 조건 (Acceptance Criteria)

- [ ] 네이버 지도 API를 사용하기 위한 초기 설정을 완료한다. #107
- [ ] 화면에 지도가 표시 된다. #108
- [ ] 지도 위에 다른 컴포넌트가 배치된다. #109
- [ ] 상단에 뒤로가기 버튼과 드로워가 있는 헤더가 존재한다. #112
- [ ] 뒤로가기 버튼을 구현한다.# 110
- [ ] 드로워를 구현한다. #111
- [ ] 우측 하단에 현재 채널에 접속한 사용자를 표시한다. #114
- [ ] 우측 하단에 현재 채널에 접속한 사용자가 색상별로 표시된다. #113
- [ ] 사용자 별 현재 위치와 경로, 도착 위치가 표시되어야 한다. #115
- [ ] 권한이 없을 경우 할머니에게 자신의 경로만 보이게, 권한이 없는 경우를 대비하여 default 값이 1인 기준으로 설정되어 있다. #116

## 💡 참고 자료 (선택)

Figma의 기획서(최종) #4 참고
